FROM node:0.12
ENV npm_config_spin=false npm_config_loglevel=http
RUN apt-get update && apt-get install libkrb5-dev
RUN npm cache clean && npm install -g grunt-cli gulp node-pre-gyp node-gyp node-inspector pm2 rimraf
EXPOSE 8080
CMD ["bash"]
